config/routes.rb
Daylog::Application.routes.draw do

  root 'logs#home', :as => :root
  get 'logs/today' => 'logs#today', :as => :today_log

  resources :logs

  get 'auth/:provider/callback' => 'sessions#callback'
  get '/logout'                 => 'sessions#destroy', :as => :logout

  post '/check_mobile_login'     => 'session#check_mobile_login'

end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user 
  validates :log_day, presence: true, uniqueness: { scope: :user_id }
  validates :motivation, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 6 }
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :logs
  def self.create_with_omniauth(auth)
    create!do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]

      if user.provider == "facebook"
         user.name = auth["info"]["name"]
      else
         user.name = auth["info"]["nickname"]
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

  helper_method :require_authentication
  helper_method :current_user
  helper_method :mobile_user

  def require_authentication
    if current_user
      return
    elsif mobile_user
      return
    end
    respond_to do |format|
      format.html { redirect_to root_path, notice: "ログインしてください" }
      format.json { render json: "ログインしてください", status: :forbidden }
    end
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # 一度current_userになれば次回以降は許可される
  end

  def mobile_user
    if @mobile_user
      return
    end

    unless token = request.headers["Authorization"]
      return
    end


    fb_user = FbGraph::User.me(token)
    fb_user = fb_user.fetch

    user = User.find_by_uid(fb_user.identifier)

    session[:user_id] = user.id

    @current_user=user

  end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :require_authentication, except: :home
  before_action :set_user
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /
  def home 
  end
  # GET /logs
  # GET /logs.json
  def index
    unless @user.nil?
      if current_user == @user
        @logs = Log.where(user_id: @user.id).order(:log_day).reverse_order
      end
    end
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @log = Log.new(log_day: Date.today, motivation: 1)
  end
  # GET /logs/today
  def today
    unless @log = @user.logs.where(log_day: Date.today).take
      @log = @user.logs.build(log_day: Date.today)
      render action: 'new'
    else
      render action: 'edit'
    end
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @log = @user.logs.new(log_params)

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render action: 'show', status: :created, location: @log }
      else
        format.html { render action: 'new' }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if current_user
        @user = current_user
      elsif mobile_user
        @user = mobile_user
      end
    end

    def set_log
      @log = Log.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_params
      params.require(:log).permit(:log_day, :positive_thing, :idea, :thought_again, :remember, :motivation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback

    #omniauth.auth環境変数を取得
    auth = request.env["omniauth.auth"]

    #Userモデルを検索
    # user = User.find_by_provider_and_uid(auth["provider"], auth["uid"])
    user = User.where(provider: auth["provider"], uid: auth["uid"]).first

    if user
      # 既存のユーザ情報があった場合ルートに遷移させます
      # sessionの作成
       session[:user_id] = user.id
       redirect_to logs_path, :notice => "ログインしました。"
    else
       # Userモデルに:providerと:uidが無い場合（外部認証していない）、保存してからルートへ遷移させる
       User.create_with_omniauth(auth)
       redirect_to logs_path, :notice => "#{auth["info"]["name"]}さんの#{auth["provider"]}アカウントと接続しました。"
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "ログアウトしました"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daylog</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body style="padding-top:70px;">
    <%= render partial: 'navbar' %>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <% if current_user %>
        <%= yield %>
      <% end %>
    </div>
  </body>
</html>

app/views/logs/_form.html.erb
<%= simple_form_for(@log) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :log_day, as: :date  %>
    <%= f.input :positive_thing, as: :text %>
    <%= f.input :idea, as: :text %>
    <%= f.input :thought_again, as: :text %>
    <%= f.input :remember, as: :text %>
    <%= f.input :motivation, collection: (1..5) %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/logs/_navbar.html.erb
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "DayLog", logs_path, :class => "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li <%= "class = active" if current_page?(logs_path) %> > <%= link_to 'Index', logs_path%> </li>
          <li <%= "class = active" if current_page?(new_log_path) %> > <%= link_to 'Create Log', new_log_path %> </li>
          <li <%= "class = active" if current_page?(today_log_path) %> > <%= link_to 'Today Log', today_log_path %> </li>
        </ul>
        <!-- <form class="navbar&#45;form navbar&#45;left" role="search"> -->
        <!--   <div class="form&#45;group"> -->
        <!--     <input type="text" class="form&#45;control" placeholder="Search"> -->
        <!--   </div> -->
        <!--   <button type="submit" class="btn btn&#45;default">Submit</button> -->
        <!-- </form> -->
        <ul class="nav navbar-nav navbar-right" style="margin-right:40px;">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user ? "#{current_user.name}" : "Sign up/Login" %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% if current_user %>
                <li><%= link_to "Logout" ,logout_path %></li>
                <li class="divider clearfix visible-xs-block"></li>
                <li class="clearfix visible-xs-block">
                  <a class="btn btn-primary" href="https://dply.me/q0l5hi#install" target="_blank">Download NativeApp <br><img src="https://dply.me/qjdy1a/button/large" alt="Try it on your device via DeployGate"></a>

                </li>
              <% else %>
                <li> <%= link_to "facebookでLogin", "/auth/facebook" %> </li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render 'form' %>

<%= link_to 'Show', @log %> |
<%= link_to 'Back', logs_path %>

app/views/logs/home.html.erb
<h1>DayLog Home</h1>

<p><%= link_to 'index', logs_path %></p>

app/views/logs/index.html.erb
<% if current_user %>
  </div>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Log day</th>
        <th>Motivation</th>
        <th>Positive thing</th>
        <th>Idea</th>
        <th>Thought again</th>
        <th>Remember</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @logs.each do |log| %>
        <tr>
          <td style="white-space:nowrap;"><%= log.log_day %></td>
          <td><%= log.motivation %></td>
          <td style="word-break: break-word;white-space: pre-line;"><%= log.positive_thing %></td>
          <td style="word-break: break-word;white-space: pre-line;"><%= log.idea %></td>
          <td style="word-break: break-word;white-space: pre-line;"><%= log.thought_again %></td>
          <td style="word-break: break-word;white-space: pre-line;"><%= log.remember %></td>
          <td><%= link_to 'Show', log %><br>
            <%= link_to 'Edit', edit_log_path(log) %><br>
            <%= link_to 'Destroy', log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render 'form' %>

<%= link_to 'Back', logs_path %>

app/views/logs/show.html.erb
<p>
  <strong>Log day:</strong>
  <%= @log.log_day %>
</p>

<p>
  <strong>Positive thing:</strong>
  <%= @log.positive_thing %>
</p>

<p>
  <strong>Idea:</strong>
  <%= @log.idea %>
</p>

<p>
  <strong>Thought again:</strong>
  <%= @log.thought_again %>
</p>

<p>
  <strong>Remember:</strong>
  <%= @log.remember %>
</p>

<p>
  <strong>Motivation:</strong>
  <%= @log.motivation %>
</p>

<%= link_to 'Edit', edit_log_path(@log) %> |
<%= link_to 'Back', logs_path %>